src/Xena.Contracts/Domain/SubscriptionInvoiceDto.cs

Minor change from Xena

---

src/Xena.Contracts/Domain/AccountantResourceTempAccessDto.cs
src/Xena.Contracts/Domain/DiscountCodeDto.cs
src/Xena.Contracts/Domain/DiscountCode_XenaAppDto.cs
src/Xena.Contracts/Domain/XenaProviderReleaseNotesLinkDto.cs
src/Xena.Contracts/Helpers/AvailableDefaultReportLayoutDto.cs
src/Xena.Contracts/Helpers/InstalledAppDto.cs
src/Xena.Contracts/Reports/FiscalBalance/CaseWarePartnerPostDto.cs
src/Xena.Contracts/Xena.Contracts.csproj

Fixes some properties with protected setters
Other:

Fixes some properties with protected setters

---

src/Xena.Contracts/Xena.Contracts.csproj

Fixes nowarn in csproj

---

src/Xena.Contracts/Domain/ClientExternalArticleProviderDto.cs
src/Xena.Contracts/Domain/ProviderExternalArticleProviderDto.cs

- Added a external article provider setup page for provider and made fiscal setups use that setup for their provider chosing
Other:

brs-1188 - Set up Gaia suppliers on provider

---

src/Xena.Contracts/Helpers/OrderTaskPostByOrderReportData.cs

- Added property for filtering order no on cost post project report
Other:

Brs 1079 - Added filter on order to Cost Post project report.

---

src/Xena.Contracts/Helpers/ResourcePostReportData.cs

- Fixed PDF and CSV in project report
Other:

brs-1082 | Fixed PDF and CSV in project report

---

src/Xena.Contracts/Domain/LedgerLineDto.cs

- Added property for partially settlled partner post.
Other:

#JIRA BRS-382 | Added property for partially settlled partner post

---

src/Xena.Contracts/Domain/PartnerPostDto.cs

- Corrected propertyname.
Other:

Corrected propertyname

---

src/Xena.Contracts/Helpers/PartnerSupplierBalanceData.cs

- Added missing property.
Other:

Added missing property

---

src/Xena.Contracts/Domain/ArticleDto.cs
src/Xena.Contracts/Helpers/ArticleMarginData.cs
src/Xena.Contracts/Helpers/HistoricStockValueData.cs
src/Xena.Contracts/Helpers/PartnerArticleStatisticsData.cs

Added support for null groupId
Other:

Added support for null groupId

---

Jenkinsfile
src/Xena.Contracts/Domain/PartnerPostDto.cs
src/Xena.Contracts/Domain/PartnerPostPaymentDto.cs
src/Xena.Contracts/Domain/PaymentDto.cs
src/Xena.Contracts/Domain/PaymentExportDraftData.cs
src/Xena.Contracts/Domain/PaymentExportedDto.cs
src/Xena.Contracts/Helpers/PaymentData.cs
src/Xena.Contracts/Helpers/PaymentDetailData.cs

- Updated Dto's to match new functionality
GDPR
======
Other:

#JIRA BRS-387 | Partial Payments - adjustment of payments

---

src/Xena.Contracts/Domain/PartnerReminderDto.cs
src/Xena.Contracts/Xena.Contracts.csproj

- Fixed payment view.
GDPR
======
Other:

#JIRA BRS-397 | Fixed payment view

---

src/Xena.Contracts/Helpers/PartnerPostReportData.cs

- Added parameter to export/reports.
GDPR
======
Other:

#JIRA BRS-1639 | Added parameter to export/reports

---

src/Xena.Contracts/Domain/OrderStatusDto.cs

- Added Dto-support.
GDPR
======
Other:

#JIRA BRS-921 | Added Dto-support

---

src/Xena.Contracts/Helpers/EmailData.cs

- Added Dto for emails.
GDPR
======
Other:

#JIRA BRS-1654 | Added Dto for emails

---

src/Xena.Contracts/Domain/SupporterDto.cs
src/Xena.Contracts/Domain/XenaUserMembershipDto.cs

BRS-1753: Prefixed blob with API

---

src/Xena.Contracts/Xena.Contracts.csproj

- Package update
GDPR
======
Other:

Package update

---

src/Xena.Contracts/Xena.Contracts.csproj

- Enables Xml documentation in Release builds.
GDPR
======
Other:

Enables Xml documentation in Release builds

---

src/Xena.Contracts/Helpers/ConfirmationCreateData.cs
src/Xena.Contracts/Helpers/OfferCreateData.cs
src/Xena.Contracts/Helpers/OrderDeliverData.cs
src/Xena.Contracts/Xena.Contracts.csproj

- Production Release 2019-05-15
GDPR
======
Other:

Production Release 2019-05-15

---

src/Xena.Contracts/ApiRoutes/FiscalSetupRoutes.cs

- Added new route for sending caseware emails 
GDPR
======
Other:

added new AccountCaseware route

---

src/Xena.Contracts/ApiRoutes/OrderTaskRoutes.cs
src/Xena.Contracts/Domain/CompositeOrderTaskDto.cs

- Added composite structure to routes and as a DTO in Contracts
GDPR
======
Other:

BRS-2029 | Added composite structure to routes and as a DTO in Contracts

---

src/Xena.Contracts/ApiRoutes/OrderTaskRoutes.cs

- Refactored name of OrderTask Composite
GDPR
======
Other:

BRS-2029 | Refactored name of OrderTask Composite

---

src/Xena.Contracts/Search/OrderSearchIndex.cs

- Added bearerId, departmentId and purposeId to OrderSearchIndex
GDPR
======
Other:

BRS-1463 - Added bearerId, departmentId and purposeId to OrderSearchIndex

---

src/Xena.Contracts/Xena.Contracts.csproj

- Updated Xena.Common.
GDPR
======
Other:

#JIRA: BRS-1890 | Updated Xena.Common

---

src/Xena.Contracts/Domain/PartnerLocationDto.cs

- Adds nullable to Longitude and Latitude
GDPR
======
Other:

Adds nullable to Longitude and Latitude

---

src/Xena.Contracts/Helpers/VatReconciliationTotalData.cs

- Added totals datatype.
GDPR
======
Other:

#JIRA BRS-2063 | Added totals datatype

---

src/Xena.Contracts/ApiRoutes/TransactionRoutes.cs

- Added route.
GDPR
======
Other:

#JIRA: brs-2063 | Added route

---

src/Xena.Contracts/Xena.Contracts.csproj

- Package update.
GDPR
======
Other:

#JIRA BRS-2456 | Package update

---

src/Xena.Contracts/Domain/CostTypeDto.cs
src/Xena.Contracts/Domain/OrderTaskLineDto.cs
src/Xena.Contracts/Domain/OrderTaskPostDto.cs
src/Xena.Contracts/Helpers/CostTypeStatisticsData.cs

- Updated dtos.
GDPR
======
Other:

#JIRA BRS-1966 | Updated dtos

---

src/Xena.Contracts/ApiRoutes/TransactionRoutes.cs
src/Xena.Contracts/Helpers/RenderVatReconciliationReportData.cs
src/Xena.Contracts/Xena.Contracts.csproj

-added routes for VatReconciliation plus datamodels
GDPR
======
Other:

BRS-2063:added routes for VatReconciliation plus datamodels

---

src/Xena.Contracts/ApiRoutes/FiscalPeriodRoutes.cs

- Added new route.
GDPR
======
Other:

#JIRA BRS-2466 | Added new route

---

src/Xena.Contracts/Domain/ResourcePostDto.cs

- Added addresses to dto.
GDPR
======
Other:

#JIRA BRS-2510 | Added addresses to dto

---

src/Xena.Contracts/Helpers/VatReconciliationData.cs

- Added difference amount to VatReconciliation
GDPR
======
Other:

Brs 2063: Added difference amount to VatReconciliation

---

src/Xena.Contracts/ApiRoutes/ArticleRoutes.cs
src/Xena.Contracts/Domain/AveragePriceChangeDto.cs
src/Xena.Contracts/Xena.Contracts.csproj

- Added Dto to reflect new domain.
GDPR
======
Other:

#JIRA BRS-2472 | Added Dto to reflect new domain

---

src/Xena.Contracts/Domain/ActivityDto.cs
src/Xena.Contracts/Domain/OrderTaskLineDto.cs
src/Xena.Contracts/Domain/OrderTaskPostDto.cs

- Added new properties.
GDPR
======
Other:

#JIRA BRS-1859 | Added new properties

---

src/Xena.Contracts/Helpers/OrderTaskPostFilterModel.cs

- Added API parameters.
GDPR
======
Other:

#JIRA BRS-2518 | Added API parameters

---

src/Xena.Contracts/Domain/OrderTaskLineDto.cs

- Added ActivityTypeType to OrderTaskLineDto
GDPR
======
Other:

BRS-1954 | Added ActivityTypeType to OrderTaskLineDto

---

src/Xena.Contracts/ApiRoutes/ArticleRoutes.cs

- Added backend route.
GDPR
======
Other:

#JIRA BRS-2350 | Added backend route

---

src/Xena.Contracts/ApiRoutes/ArticleRoutes.cs
src/Xena.Contracts/Xena.Contracts.csproj

- Production Release 2019-09-02
GDPR
======
Other:

Production Release 2019-09-02

---

src/Xena.Contracts/ApiRoutes/PartnerRoutes.cs
src/Xena.Contracts/ApiRoutes/UserRoutes.cs
src/Xena.Contracts/Domain/XenaUserPartnerPostDto.cs

- Added new routes for Partner + User and changes to XenaUserPartnerPostDto
GDPR
======
Other:

Brs 2625: Added new routes for Partner + User and changes to XenaUserPartnerPostDto

---

src/Xena.Contracts/Helpers/CalculatedArticleAvailabilityTotalDto.cs

- Added property to Dto.
GDPR
======
Other:

#JIRA BRS-2669 | Added property to Dto

---

src/Xena.Contracts/Domain/OrderTaskLineDto.cs

-  Added orderId to OrderTaskLineDto
GDPR
======
Other:

Brs 2609: Added orderId to OrderTaskLineDto

---

src/Xena.Contracts/Helpers/OngoingOrdersHistoricData.cs

- added bearerId and purposeId to OngoingOrdersHistoricData
GDPR
======
Other:

Brs 2435: added bearerId and purposeId to OngoingOrdersHistoricData

---

src/Xena.Contracts/ApiRoutes/PartnerRoutes.cs
src/Xena.Contracts/Helpers/ObsoletePartnerSearchDto.cs

- Added new routes and Dto's
GDPR
======
Other:

#JIRA BRS-2757 | Added new routes and Dto's

---

src/Xena.Contracts/Domain/PaymentMeansDto.cs
src/Xena.Contracts/Xena.Contracts.csproj

- Added support for custom layout.
GDPR
======
Other:

#JIRA BRS-2759 | Added support for custom layout

---

src/Xena.Contracts/Domain/LedgerTagBankContextDto.cs
src/Xena.Contracts/Xena.Contracts.csproj

- Added new property.
GDPR
======
Other:

#JIRA BRS-2860 | Added new property

---

src/Xena.Contracts/ApiRoutes/PaymentMeansRoutes.cs

- Added GetPaymentLayoutExample route
GDPR
======
Other:

BRS-2881 | Added GetPaymentLayoutExample route

---

src/Xena.Contracts/ApiRoutes/ExternalDataRoutes.cs
src/Xena.Contracts/Search/IndexedTypes.cs
src/Xena.Contracts/Search/NorwegianCompanyIndex.cs

- Update orgno data for NO - refactor
GDPR
======
Other:

#Jira BRS-2720 - Update orgno data for NO - refactor

---

src/Xena.Contracts/Search/VirkCompanyIndex.cs

#Jira BRS-2721 | Change CompanyIndex metadata

---

src/Xena.Contracts/Search/VirkCompanyIndex.cs

#Jira BRS-2721 | Address format, email, phone

---

src/Xena.Contracts/Search/VirkCompanyIndex.cs

- Production Release 2019-10-24
GDPR
======
Other:

Production Release 2019-10-24

---

src/Xena.Contracts/ApiRoutes/LedgerLineRoutes.cs
src/Xena.Contracts/Helpers/LedgerLineBasicData.cs
src/Xena.Contracts/Helpers/LedgerLineKIDData.cs
src/Xena.Contracts/Helpers/LedgerLinePaymentData.cs

Change in name for generic using.
GDPR
======
Other:

BRS-1130 | Change KID to more generic name - BasicData

---

src/Xena.Contracts/ApiRoutes/TransactionRoutes.cs

- Added new route.
GDPR
======
Other:

#JIRA BRS-3128 | Added new route

---

src/Xena.Contracts/Helpers/SpecifiedVariantData.cs

- Corrected datatype.
GDPR
======
Other:

#JIRA BRS-2903 | Corrected datatype

---

src/Xena.Contracts/ApiRoutes/BlobFiscalRoutes.cs
src/Xena.Contracts/ApiRoutes/DocumentRelated/DocumentFolderConfigurationRoutes.cs
src/Xena.Contracts/ApiRoutes/DocumentRelated/DocumentFolderRoutes.cs
src/Xena.Contracts/ApiRoutes/DocumentRelated/DocumentRoutes.cs
src/Xena.Contracts/ApiRoutes/PartnerRoutes.cs
src/Xena.Contracts/ApiRoutes/TransactionRoutes.cs
src/Xena.Contracts/Domain/ArticleDto.cs
src/Xena.Contracts/Domain/DocumentRelated/DocumentDto.cs
src/Xena.Contracts/Domain/DocumentRelated/DocumentFolderConfigurationDto.cs
src/Xena.Contracts/Domain/DocumentRelated/DocumentFolderDto.cs
src/Xena.Contracts/Domain/DocumentRelated/DocumentRelationDto.cs
src/Xena.Contracts/Domain/DocumentRelated/DocumentVersionDto.cs
src/Xena.Contracts/Domain/FileTypeHelper.cs
src/Xena.Contracts/Domain/LocationDto.cs
src/Xena.Contracts/Domain/WarehouseDto.cs
src/Xena.Contracts/Helpers/DocumentRelated/BulkCreateDocumentFolderData.cs
src/Xena.Contracts/Helpers/DocumentRelated/CreateDocumentRelationData.cs
src/Xena.Contracts/Helpers/DocumentRelated/DocumentCountData.cs
src/Xena.Contracts/Helpers/PartnerSaldoByDueDateReportData.cs
src/Xena.Contracts/Helpers/PrimoArticlePostImportData.cs
src/Xena.Contracts/Reports/PartnerBalanceByDueDateDto.cs
src/Xena.Contracts/Search/IndexExtensions.cs
src/Xena.Contracts/Search/LocationSearchIndex.cs
src/Xena.Contracts/Xena.Contracts.csproj

Test release

---

src/Xena.Contracts/Xena.Contracts.csproj

Contracts version update

---

src/Xena.Contracts/Xena.Contracts.csproj

BRS-694 | contracts update

---

src/Xena.Contracts/Reports/SAF_T/Account.cs
src/Xena.Contracts/Reports/SAF_T/Company.cs
src/Xena.Contracts/Reports/SAF_T/Contact.cs
src/Xena.Contracts/Reports/SAF_T/ContactPerson.cs
src/Xena.Contracts/Reports/SAF_T/Customer.cs
src/Xena.Contracts/Reports/SAF_T/Supplier.cs

#Jira BRS-781 - Upcoming Norwegian requirement to deliver data in SAF-T format - subtasks

---

src/Xena.Contracts/Reports/PartnerPostDtoGroup.cs
src/Xena.Contracts/Xena.Contracts.csproj

BRS-694-2 | fix to sum on remaining amount

---

src/Xena.Contracts/Xena.Contracts.csproj

BRS-694-5 | common update

---

src/Xena.Contracts/Domain/StockCountDraftProblemDto.cs

#Jira BRS-3530 | GetCanBookkeep fix

---

src/Xena.Contracts/Search/IndexExtensions.cs
src/Xena.Contracts/Search/OrderTaskSearchIndex.cs

#Jira BRS-3444 | Backend: New OrderTask endpoint for Go & Log - putting Created Date to OrderTask index

---

src/Xena.Contracts/ApiRoutes/DocumentRelated/DocumentFolderConfigurationRoutes.cs
src/Xena.Contracts/ApiRoutes/DocumentRelated/DocumentFolderRoutes.cs
src/Xena.Contracts/Domain/DocumentRelated/DocumentFolderConfigurationDto.cs
src/Xena.Contracts/Domain/DocumentRelated/DocumentFolderDto.cs
src/Xena.Contracts/Helpers/DocumentRelated/BulkCreateDocumentFolderData.cs

#Jira BRS-20 | Removed Index, renamed EntityType to DocumentFolderType, DocumentFolderTypes in Common, CRUD for DocumentFolderConfiguration

---

src/Xena.Contracts/Helpers/OrderInvoiceAggregateDto.cs

- Adding OrderNumber property to OrderInvocieAggregateDto
GDPR
======
Other:

BRS-3790 | Adding OrderNumber property to OrderInvocieAggregateDto

---

src/Xena.Contracts/Domain/LimitedFiscalDto.cs

BRS-3858 | added view - limitedFiscalDto

---

src/Xena.Contracts/ApiRoutes/SupporterRoutes.cs
src/Xena.Contracts/Domain/LimitedFiscalDto.cs

BRS-3858 | api routes changed.
